updates: 
  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
    open-pull-requests-limit: 99
    schedule:
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: main
    commit-message: 
      include: scope
      prefix: chore
version: 2